export const STORAGE_KEYS = {
  world: "drone_sim_world",
  renderer: "drone_sim_renderer",
  camera: "drone_sim_camera",
  collision: "drone_sim_collision",
  quality: "drone_sim_quality",
  crosshair: "drone_sim_crosshair",
  horizonLine: "drone_sim_horizon_line",
  stickOverlay: "drone_sim_stick_overlay",
  audioVolume: "drone_sim_audio_volume",
  hideSettings: "fpv_hide_settings",
  resumeAfterMapChange: "fpv_resume_after_map_change",
  resumeFlightMode: "fpv_resume_flight_mode",
  resumeAutoPlay: "fpv_resume_auto_play",
  physicsPreset: "fpv_physics_preset_v1",
  gamepadCalibrationPrefix: "fpv-sim-gamepad-calibration:",
  gogglesModel: "drone_sim_goggles_model",
  gogglesAspect: "drone_sim_goggles_aspect",
} as const;
